oopsie/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from moments.views.moment_views import main

urlpatterns = [
    path('', lambda request: redirect('users:onboarding1'), name='root_redirect'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('moments/', include('moments.urls')),
    path('pages/moments/', include('moments.pages_urls', namespace='moments')),
    path('main/', main, name='main'),
]

users/urls.py
from django.urls import path
from .views.login import login_view
from .views.signup import signup_view
from .views.mypage import mypage_view
from users.views.onboarding import onboarding_view, onboarding_view2, onboarding_view3, finish_onboarding

app_name = "users"

urlpatterns = [
    path('signup/', signup_view, name='signup'),
    path('login/', login_view, name='login'),
    path('mypage/', mypage_view, name='mypage'),
    path('onboarding/1/', onboarding_view, name='onboarding1'),
    path('onboarding/2/', onboarding_view2, name='onboarding2'),
    path('onboarding/3/', onboarding_view3, name='onboarding3'),
    path('onboarding/finish/', finish_onboarding, name='finish_onboarding')
]

templates/components/navbar.html
{% load static %}

<head>
  <link rel="stylesheet" href="{% static 'css/common/navbar.css' %}">
</head>

<nav class="navbar">
  <a href="{% url 'main' %}">
    <img src="{% static 'assets/home.svg' %}" alt="홈" />
  </a>
  <a href="{% url 'moments:moment_create_view' %}">
    <img src="{% static 'assets/write.svg' %}" alt="글쓰기" />
  </a>
  <a href="{% url 'users:mypage' %}">
    <img src="{% static 'assets/profile.svg' %}" alt="프로필" />
  </a>
</nav>